### ISSUE TITLE
Boot errors: ALL LOW + Z0.0000

### ISSUE THREAD

**Issue by albertovm** [bigtreetech/BIQU-B2#3]
Hi,

I did the bigtreetech upgrade adding the B2 (hotend + extruder) in my B1 printer.
I also added another Z stepper and BLTouch.

The printer works fine with Biqu B1 firmware, but replacing it with B2 firmware I have 2 error messages:

ALL LOW
Z0.0000

Is there anything that I need to change or could be fixed in this firmware to solve this problem?
Thanks!

More info:
Octoprint shows:
Info: Firmware Development Build
Your printer's firmware is a development build of Marlin (build date 20210713). It might be more unstable than a release version and should be kept up-to-date.

**Comment by albertovm** [comment]
It was jumper position in latest installed stepper.

**Comment by bjuraga** [comment]
I just hit thebsame issue and would love to know which jumper in which position.  Thanks!

I also tried a print and got a bunch of unknown gcode errors, having the nozzle scrape on the side of the bed, but printer was leveled before.
